/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>

#line 1 "tests.check"
#include <libft.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include "helpers.h"

START_TEST(test_atoi)
{
#line 8
	fail_unless(ft_atoi("42") == 42, "atoi failed for positive number");
	fail_unless(ft_atoi("0") == 0, "atoi failed for 0");
	fail_unless(ft_atoi("-42") == -42, "atoi failed for negative number");

}
END_TEST

START_TEST(test_bzero)
{
#line 13
	int sz = sizeof("jambon");
	char* str = strdup("jambon");
	ft_bzero(str, sz - 1);
	int i = 0;
	while (i < sz)
	{
		fail_unless(str[i] == '\0', "some character is not '\\0'");
		i++;
	}
	free(str);

}
END_TEST

START_TEST(test_isalnum)
{
#line 25
	char c = -128;
	while (c < 127)
	{
		fail_unless(ft_isalnum(c) == isalnum(c), "output differ from stdlib");
		c++;
	}

}
END_TEST

START_TEST(test_isalpha)
{
#line 33
	char c = -128;
	while (c < 127)
	{
		fail_unless(ft_isalpha(c) == isalpha(c), "output differ from stdlib");
		c++;
	}

}
END_TEST

START_TEST(test_isascii)
{
#line 41
	char c = -128;
	while (c < 127)
	{
		fail_unless(ft_isascii(c) == isascii(c), "output differ from stdlib");
		c++;
	}

}
END_TEST

START_TEST(test_isdigit)
{
#line 49
	char c = -128;
	while (c < 127)
	{
		fail_unless(ft_isdigit(c) == isdigit(c), "output differ from stdlib");
		c++;
	}

}
END_TEST

START_TEST(test_isprint)
{
#line 57
	char c = -128;
	while (c < 127)
	{
		fail_unless(ft_isprint(c) == isprint(c), "output differ from stdlib");
		c++;
	}

}
END_TEST

START_TEST(test_itoa)
{
#line 65
	char* result;
	result = ft_itoa(42);
	fail_unless(strcmp(result, "42") == 0, "itoa failed for positive number");
	free(result);
	result = ft_itoa(0);
	fail_unless(strcmp(result, "0") == 0, "itoa failed for 0");
	free(result);
	result = ft_itoa(-42);
	fail_unless(strcmp(result, "-42") == 0, "itoa failed for negative number");
	free(result);

}
END_TEST

START_TEST(test_lstnew)
{
#line 77
	t_list* lst = ft_lstnew(NULL, 42);
	fail_unless(lst->content == NULL, "lstnew did not set content to NULL");
	fail_unless(lst->content_size == 0, "lstnew did not set content_size to 0");
	free(lst);
	size_t sz = sizeof("jambon");
	char* ptr = "jambon";
	lst = ft_lstnew(ptr, 7);
	fail_unless(lst->next == NULL, "lstnew did not set next to NULL");
	fail_unless(lst->content != ptr, "lstnew did not make a copy");
	fail_unless(lst->content_size == sz, "lstnew failed to copy the content size");
	fail_unless(strcmp(lst->content, ptr) == 0, "lstnew failed to copy the content");

}
END_TEST

START_TEST(test_lstdelone)
{
#line 90
	t_list* lst = ft_lstnew(NULL, 0);
	t_list* next = ft_lstnew(NULL, 0);
	lst->next = next;
	ft_lstdelone(&lst, del_lst_content);
	fail_unless(lst == NULL);
	free(next);

}
END_TEST

START_TEST(test_lstdel)
{
#line 98
	t_list* lst = ft_lstnew(NULL, 0);
	t_list* next = ft_lstnew(NULL, 0);
	lst->next = next;
	ft_lstdel(&lst, del_lst_content);
	fail_unless(lst == NULL);

}
END_TEST

START_TEST(test_lstadd)
{
#line 105

}
END_TEST

START_TEST(test_lstiter)
{
#line 107

}
END_TEST

START_TEST(test_lstmap)
{
#line 109

}
END_TEST

START_TEST(test_memalloc)
{
#line 111

}
END_TEST

START_TEST(test_memccpy)
{
#line 113

}
END_TEST

START_TEST(test_memchr)
{
#line 115

}
END_TEST

START_TEST(test_memcmp)
{
#line 117

}
END_TEST

START_TEST(test_memcpy)
{
#line 119

}
END_TEST

START_TEST(test_memdel)
{
#line 121

}
END_TEST

START_TEST(test_memmove)
{
#line 123

}
END_TEST

START_TEST(test_memset)
{
#line 125

}
END_TEST

START_TEST(test_putchar)
{
#line 127

}
END_TEST

START_TEST(test_putchar_fd)
{
#line 129

}
END_TEST

START_TEST(test_putendl)
{
#line 131

}
END_TEST

START_TEST(test_putendl_fd)
{
#line 133

}
END_TEST

START_TEST(test_putnbr)
{
#line 135

}
END_TEST

START_TEST(test_putnbr_fd)
{
#line 137

}
END_TEST

START_TEST(test_putstr)
{
#line 139

}
END_TEST

START_TEST(test_putstr_fd)
{
#line 141

}
END_TEST

START_TEST(test_strcat)
{
#line 143

}
END_TEST

START_TEST(test_strchr)
{
#line 145

}
END_TEST

START_TEST(test_strclr)
{
#line 147

}
END_TEST

START_TEST(test_strcmp)
{
#line 149

}
END_TEST

START_TEST(test_strcpy)
{
#line 151

}
END_TEST

START_TEST(test_strdel)
{
#line 153

}
END_TEST

START_TEST(test_strdup)
{
#line 155

}
END_TEST

START_TEST(test_strequ)
{
#line 157

}
END_TEST

START_TEST(test_striter)
{
#line 159

}
END_TEST

START_TEST(test_striteri)
{
#line 161

}
END_TEST

START_TEST(test_strjoin)
{
#line 163

}
END_TEST

START_TEST(test_strlcat)
{
#line 165

}
END_TEST

START_TEST(test_strlen)
{
#line 167

}
END_TEST

START_TEST(test_strmap)
{
#line 169

}
END_TEST

START_TEST(test_strmapi)
{
#line 171

}
END_TEST

START_TEST(test_strncat)
{
#line 173

}
END_TEST

START_TEST(test_strncmp)
{
#line 175

}
END_TEST

START_TEST(test_strncpy)
{
#line 177

}
END_TEST

START_TEST(test_strnequ)
{
#line 179

}
END_TEST

START_TEST(test_strnew)
{
#line 181

}
END_TEST

START_TEST(test_strnstr)
{
#line 183

}
END_TEST

START_TEST(test_strrchr)
{
#line 185

}
END_TEST

START_TEST(test_strsplit)
{
#line 187

}
END_TEST

START_TEST(test_strstr)
{
#line 189

}
END_TEST

START_TEST(test_strsub)
{
#line 191

}
END_TEST

START_TEST(test_strtrim)
{
#line 193

}
END_TEST

START_TEST(test_tolower)
{
#line 195

}
END_TEST

START_TEST(test_toupper)
{
#line 197
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_atoi);
    tcase_add_test(tc1_1, test_bzero);
    tcase_add_test(tc1_1, test_isalnum);
    tcase_add_test(tc1_1, test_isalpha);
    tcase_add_test(tc1_1, test_isascii);
    tcase_add_test(tc1_1, test_isdigit);
    tcase_add_test(tc1_1, test_isprint);
    tcase_add_test(tc1_1, test_itoa);
    tcase_add_test(tc1_1, test_lstnew);
    tcase_add_test(tc1_1, test_lstdelone);
    tcase_add_test(tc1_1, test_lstdel);
    tcase_add_test(tc1_1, test_lstadd);
    tcase_add_test(tc1_1, test_lstiter);
    tcase_add_test(tc1_1, test_lstmap);
    tcase_add_test(tc1_1, test_memalloc);
    tcase_add_test(tc1_1, test_memccpy);
    tcase_add_test(tc1_1, test_memchr);
    tcase_add_test(tc1_1, test_memcmp);
    tcase_add_test(tc1_1, test_memcpy);
    tcase_add_test(tc1_1, test_memdel);
    tcase_add_test(tc1_1, test_memmove);
    tcase_add_test(tc1_1, test_memset);
    tcase_add_test(tc1_1, test_putchar);
    tcase_add_test(tc1_1, test_putchar_fd);
    tcase_add_test(tc1_1, test_putendl);
    tcase_add_test(tc1_1, test_putendl_fd);
    tcase_add_test(tc1_1, test_putnbr);
    tcase_add_test(tc1_1, test_putnbr_fd);
    tcase_add_test(tc1_1, test_putstr);
    tcase_add_test(tc1_1, test_putstr_fd);
    tcase_add_test(tc1_1, test_strcat);
    tcase_add_test(tc1_1, test_strchr);
    tcase_add_test(tc1_1, test_strclr);
    tcase_add_test(tc1_1, test_strcmp);
    tcase_add_test(tc1_1, test_strcpy);
    tcase_add_test(tc1_1, test_strdel);
    tcase_add_test(tc1_1, test_strdup);
    tcase_add_test(tc1_1, test_strequ);
    tcase_add_test(tc1_1, test_striter);
    tcase_add_test(tc1_1, test_striteri);
    tcase_add_test(tc1_1, test_strjoin);
    tcase_add_test(tc1_1, test_strlcat);
    tcase_add_test(tc1_1, test_strlen);
    tcase_add_test(tc1_1, test_strmap);
    tcase_add_test(tc1_1, test_strmapi);
    tcase_add_test(tc1_1, test_strncat);
    tcase_add_test(tc1_1, test_strncmp);
    tcase_add_test(tc1_1, test_strncpy);
    tcase_add_test(tc1_1, test_strnequ);
    tcase_add_test(tc1_1, test_strnew);
    tcase_add_test(tc1_1, test_strnstr);
    tcase_add_test(tc1_1, test_strrchr);
    tcase_add_test(tc1_1, test_strsplit);
    tcase_add_test(tc1_1, test_strstr);
    tcase_add_test(tc1_1, test_strsub);
    tcase_add_test(tc1_1, test_strtrim);
    tcase_add_test(tc1_1, test_tolower);
    tcase_add_test(tc1_1, test_toupper);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
